Template 3 - Mobile version skeleton
TEMESGEN-G25/Portfoli pull request #1
Opened 2022-01-07 17:31 UTC by NatiG25

In this project I:
- Added one HTML file & one CSS file.
- A mobile skeleton from one of MIcroverse's figma templates.
- Added icons from font awesome.

2022-01-07 17:36 UTC, aliabbani reviewed
Hi @NatiG25 ✋  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The linter in your repository should always be green, Please solve the Stylelint errors and submit again 😊 .

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-07 18:16 UTC, Lordkaito reviewed
Hi @NatiG25 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not passed linters. Please make sure to correct this before asking for a new code review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-07 19:30 UTC, mike2611 requested changes
Hi @NatiG25 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not passed linters. Please make sure to correct this before asking for a new code review.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-07 20:48 UTC, VICTOR-CHUKWU requested changes
Hi @NatiG25  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 20:48 UTC, VICTOR-CHUKWU commented on index.html
> +      <img src="image/Union.svg" alt="Menu-button" class="hamburger-menu">
- [ ] you did well but I think you can still improve your code by using semantic elements. I suggest you use the `nav` to wrap the `image` tag at line 14. Please, make sure that your name is also wrapped in an anchor `a` element. By this, your name will be clickable and navigates to wherever you may want to take the users.
   Example
   ```
     <header class="header">
      <a href="" class="logo">Welcome</a>
      <nav><img src="image/Union.svg" alt="Menu-button" class="hamburger-menu"></nav>
    </header>
 ```

2022-01-07 20:48 UTC, VICTOR-CHUKWU commented on index.html
> +        <i class="fab fa-medium-m"></i>
- [ ] Following project requiremnets, kindly wrap your icons in `ul` element with each icons inside `a` tag, this makes your social icons clickable and can navigate to the particular link when clicked. your code should look like this
```
<ul>
<li><a href=""><i class="fab fa-github"></i></a></li>
<li><a href=""> <i class="fab fa-linkedin-in"></i></a></li>
<li><a href=""><i class="far fa-hand-peace"></i></a></li>
<li><a href=""><i class="fas fa-dove"></i></a></li>
<li><a href=""><i class="fab fa-medium-m"></i></a></li>
</ul>

2022-01-07 20:48 UTC, VICTOR-CHUKWU commented on index.html
> +    <header class="header">
- [ ] t is a good practice for a frontend developer to follow the Figma design given. Though your design is not bad, I think it is better to follow the given mobile menu design.
  your design 👇 
         
![image](https://user-images.githubusercontent.com/66097371/148605099-c7561fee-5366-4a05-9337-d9a59a97b72d.png)
 Figma design 👇 
      
![image](https://user-images.githubusercontent.com/66097371/148605220-032afdee-4522-4207-bd1d-6f8e37186aea.png)

2022-01-07 23:00 UTC, Amrhub requested changes
Hi @NatiG25, 👋🏻 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 23:00 UTC, Amrhub commented on index.html
> +      <a href="" class="logo">Welcome</a>
- [ ] when using `<a>` anchor tag by default it has `text-decoration: underline` as CSS property we need to disable that to make sure we match Figma design

2022-01-07 23:00 UTC, Amrhub commented on index.html
> +        </ul>
- [ ] when using `ul` we need to make sure we understand it has default CSS properties as well
1- it list item vertically 
2- it adds a bullet listing using the `list-style` property in CSS 
let's make sure we follow the design

Yours | Figma design
:--:|:--:
![image](https://user-images.githubusercontent.com/87689547/148617826-af16d31e-d38d-40c8-a632-a628754dc7e3.png) | ![image](https://user-images.githubusercontent.com/87689547/148617857-f5b10abd-b213-45b7-b61b-f4be05b73640.png)

2022-01-08 07:49 UTC, rotimiazeez approved these changes
# Hi @NatiG25 , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 07:51 UTC, merged